name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Agent
        run: |
          echo "## Setting up SSH"
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Upload Code (Optional)
        run: |
          echo "## Uploading code via SSH"
          scp -o StrictHostKeyChecking=no -r . arjun@${{ secrets.SERVER_IP }}:/var/www/html 

      - name: Use gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: principal-oxide-400310

      - name: Restart Nginx
        run: |
          echo "## Restarting Nginx"
          gcloud ssh arjun@${{ secrets.SERVER_IP }} --command "sudo systemctl restart nginx"
