name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v1'
        with:
          instance_name: 'actionsdemo'
          zone: 'asia-south1-c'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          command: 
            scp -o StrictHostKeyChecking=no -r . arjun@${{ secrets.SERVER_IP }}:/var/www/html 
            sudo chown -R arjun:nginx /var/www/html
            sudo chmod -R 644 /var/www/html/*
            sudo systemctl restart nginx
